/*
- push adiciona um elemento ao final do array
- unshift adiciona um elemento ao inicio do array
- shift remove o primeiro elemento do array
- pop remove o ultimo elemento do array
- splice remove um elemento do array
- slice retorna uma parte do array
- concat concatena dois arrays
- join transforma um array em uma string
- reverse inverte a ordem dos elementos do array
- sort ordena os elementos do array
- forEach executa uma função para cada elemento do array
- map cria um novo array com os resultados da função aplicada a cada elemento do array
- filter cria um novo array com os elementos que passaram no teste da função
- find retorna o primeiro elemento que passou no teste da função
- reduce aplica uma função a cada elemento do array, retornando um único valor
- includes verifica se o array contém um elemento
- indexOf retorna o índice do primeiro elemento que passou no teste da função
- every verifica se todos os elementos do array passaram no teste da função
- some verifica se pelo menos um elemento do array passou no teste da função
- findIndex retorna o índice do primeiro elemento que passou no teste da função
- fill preenche todos os elementos do array com um valor
- copyWithin copia uma parte do array para outra parte do array
- keys retorna um array com as chaves de cada elemento do array
- values retorna um array com os valores de cada elemento do array
- entries retorna um array com os pares chave/valor de cada elemento do array
- flat retorna um novo array com todos os elementos sub-array concatenados
- flatMap mapeia cada elemento do array e depois achata o resultado em um novo array
*/
